# Generated by Django 3.2 on 2023-12-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('M', 'moderator'), ('A', 'admin'), ('U', 'user')], default='U', max_length=1),
        ),
    ]
