POST http://127.0.0.1:8000/api/v1/auth/token/
Content-Type: application/json; charset=utf8

{
"confirmation_code": "39354",
"username": "first"
}
###
"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzAyODIwNDE2LCJpYXQiOjE3MDI4MjAxMTYsImp0aSI6IjUyZTE1NjNmNzQ3MjRiZTg4ODZlODg4YjUyOTViYjNmIiwidXNlcl9pZCI6Nn0.g77Ezrod5W5aFhlQQxjZ0Q3ffHFAL2HUQofwXfN4r98"
###
POST http://127.0.0.1:8000/api/v1/titles/
Content-Type: application/json; charset=utf8

{
"name": "lol",
"year": 2020,
"description": "blabla",
"genre": [
"Роман"
],
"category": "Фильм"
}
###
GET  http://127.0.0.1:8000/api/v1/titles/
Content-Type: application/json; charset=utf8
