# Generated by Django 3.2 on 2023-12-17 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20231217_0241'),
        ('reviews', '0002_initial'),
    ]

    operations = [
    ]
